// FETCHING CRYPTO TYPE
export const START_FETCH_CRYPTO = "START_FETCH_CRYPTO";
export const FETCH_CRYPTO_SUCCESS = "FETCH_CRYPTO_SUCCESS";
export const FETCH_CRYPTO_FAILURE = "FETCH_CRYPTO_FAILURE";

// FETCHING GLOBAL TYPE
