// FETCHING CRYPTO TYPE
export const START_FETCH_CRYPTO = "START_FETCH_CRYPTO";
export const FETCH_CRYPTO_SUCCESS = "FETCH_CRYPTO_SUCCESS";
export const FETCH_CRYPTO_FAILURE = "FETCH_CRYPTO_FAILURE";

// FETCHING CHART DATA
export const START_FETCH_CHART = "START_FETCH_CHART";
export const FETCH_CHART_SUCCESS = "FETCH_CHART_SUCCESS";
export const FETCH_CHART_FAILURE = "FETCH_CHART_FAILURE";

// FETCHING GLOBAL TYPE
