// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/luu/ReacNativeProjects/CoinMarketCap/node_modules/react');
var { Component } = React;
var ReactNative = require('/Users/luu/ReacNativeProjects/CoinMarketCap/node_modules/react-native');
var { AppRegistry } = ReactNative;
var entryPoint = require('/Users/luu/ReacNativeProjects/CoinMarketCap/index.js');
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('CoinMarketCap', appParameters);
});